"""migrate

Revision ID: 8d883d7f8bf1
Revises: 8fdd3d21fb0c
Create Date: 2021-06-04 04:16:36.033053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d883d7f8bf1'
down_revision = '8fdd3d21fb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_cage_setup_date')
        batch_op.create_index(batch_op.f('ix_cage_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('setup_date')

    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_mouse_dob')
        batch_op.create_index(batch_op.f('ix_mouse_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mouse_timestamp'))
        batch_op.create_index('ix_mouse_dob', ['dob'], unique=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('cage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setup_date', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_cage_timestamp'))
        batch_op.create_index('ix_cage_setup_date', ['setup_date'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
