"""migrate

Revision ID: 8fdd3d21fb0c
Revises: 91778bec4909
Create Date: 2021-06-03 23:42:24.613204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdd3d21fb0c'
down_revision = '91778bec4909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cagetag', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse', schema=None) as batch_op:
        batch_op.drop_column('cagetag')

    # ### end Alembic commands ###
